image:
  name: $DOCKER_REGISTRY_USERNAME/atlassian-default-image-wterraform:latest
  username: $DOCKER_REGISTRY_USERNAME
  password: $DOCKER_REGISTRY_PASSWORD

pipelines:
  default:
    - step:
        name: terraform-jobs
        script:
          - terraform -chdir="src" init 
          - terraform -chdir="src" plan
          - terraform -chdir="src" apply -auto-approve
