image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: build docker image
        script:
          - docker build -t bitbucket-cibase:linsync-1.0.1-alpha .
        services:
          - docker